### PR TITLE
Fix #34: Fix template compilation mode.

### LINKED ISSUE #34: Compilation system is all messed up
Currently the lazy compilation model is all messed up and need to get reworked.

It will now default to Production mode where all files are just compiled in. The template will just keep track of what files were compiled and so if it is flipped to Development mode, it will just recompile everything all the time.

### PR DESCRIPTION
**Pull request by zeebo**
More tests to make sure it does as advertised coming.

### CODE REVIEW

File: template.go [hunk 1]
```diff
@@ -22,8 +22,8 @@ func (m Mode) String() string {
 }
 
 const (
-	Development Mode = false
-	Production  Mode = true
+	Development Mode = true
+	Production  Mode = false
```
Comment (zeebo) [inline template.go:26]: Easy flip. Hehe

**Comment by jbaikge** [comment]
Looks sound to me, ready for mergery
